# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f validator/Dockerfile-installed-bionic -t sawtooth-validator .

# -------------=== validator build ===-------------
FROM ubuntu:bionic as sawtooth-validator-builder

RUN apt-get update \
 && apt-get install gnupg -y

ENV VERSION=AUTO_STRICT

RUN echo "deb http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && apt-get install -y -q \
    git \
    libssl-dev \
    libzmq3-dev \
    openssl \
    pkg-config \
    python3 \
    python3-cachetools \
    python3-dev \
    python3-protobuf \
    python3-stdeb \
    python3-pip \
    python3-toml \
    unzip

RUN apt-get install -y -q build-essential automake pkg-config libtool libffi-dev

RUN python3 -m pip install pyformance grpcio grpcio-tools sawtooth-sdk secp256k1

RUN curl -OLsS https://github.com/protocolbuffers/protobuf/releases/download/v3.19.4/protoc-3.19.4-linux-aarch_64.zip \
 && unzip protoc-3.19.4-linux-aarch_64.zip -d protoc3 \
 && rm protoc-3.19.4-linux-aarch_64.zip

RUN curl https://sh.rustup.rs -sSf > /usr/bin/rustup-init \
 && chmod +x /usr/bin/rustup-init \
 && rustup-init -y

ENV PATH=$PATH:/project/sawtooth-core/bin:/protoc3/bin:/project/sawtooth-core/bin:/root/.cargo/bin \
    CARGO_INCREMENTAL=0

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /project

COPY . /project

RUN python3 /project/bin/protogen \
 && cd /project/validator \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi \
 && if [ -d "bin" ]; then rm -rf bin; fi \
 && mkdir bin \
 && if [ -d "lib" ]; then rm -rf lib; fi \
 && mkdir lib \
 && sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"1.99.1-dev1\"/" Cargo.toml \
 && cargo build --release \
 && cp ./target/release/sawtooth-validator bin/sawtooth-validator \
 && cp ./target/release/libsawtooth_validator.so lib/libsawtooth_validator.so \
 && dpkg-buildpackage -b -rfakeroot -us -uc


# -------------=== cli build ===-------------
FROM ubuntu:bionic as sawtooth-cli-builder

RUN apt-get update \
 && apt-get install gnupg -y

ENV VERSION=AUTO_STRICT

RUN echo "deb http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && apt-get install -y -q \
    git \
    python3 \
    python3-protobuf \
    libzmq3-dev \
    python3-stdeb \
    python3-toml \
    python3-pip

RUN apt-get install -y -q python3-dev

RUN apt-get install -y -q build-essential automake pkg-config libtool libffi-dev

RUN python3 -m pip install grpcio
RUN python3 -m pip install grpcio-tools
RUN python3 -m pip install sawtooth-sdk

COPY . /project

RUN /project/bin/protogen \
 && cd /project/cli \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi \
 && dpkg-buildpackage -b -rfakeroot -us -uc

# -------------=== sawtooth-validator docker build ===-------------
FROM ubuntu:bionic

RUN apt-get update \
 && apt-get install -y \
 gnupg \
 libzmq3-dev \
 systemd \
 python3 \
 python3-pip

RUN echo SHIT

RUN apt-get install -y -q build-essential automake pkg-config libtool libffi-dev libzmq3-dev
RUN python3 -m pip install packaging sawtooth-sdk
RUN python3 -m pip install pyformance protobuf
RUN apt-get install -y -q python3-protobuf
RUN apt-get install -y -q python3-aiodns python3-aiohttp python3-stdeb
RUN python3 -m pip install cchardet
RUN apt-get install -y -q python3-toml
ENV PATH=$PATH:/project/sawtooth-core/bin
RUN apt-get install -y -q python3-dev
RUN python3 -m pip install grpcio grpcio-tools

WORKDIR /project
COPY . /project

RUN echo "\033[0;32m--- Building cli ---\n\033[0m" \
 && python3 bin/protogen \
 && cd cli \
 && python3 setup.py clean --all \
 && python3 setup.py build \
 && python3 setup.py install


COPY --from=sawtooth-cli-builder /project/python3-sawtooth-cli*.deb /tmp

COPY --from=sawtooth-validator-builder /project/python3-sawtooth-validator*.deb /tmp

RUN echo "deb http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && dpkg -i /tmp/python3-sawtooth-*.deb || true \
 && apt-get -f -y install
